### ISSUE TITLE
GUI Security Features

### ISSUE THREAD

**Issue by adamkrellenstein** [towercomputers/toweros#107]
- Window Borders
- Clipboard Management
- ~Information Flow Control~
- Shell Prompt

**Comment by ouziel-slama** [comment]
- Window Borders

It seems complicated to do that without specific work on each application. Especially because of the differences between the graphics libraries used by the applications which also do not always respect the standards of the library used. I think we should run the application inside a container whose appearance we would control.. but I don't really know how to do that at the moment, especially with NX.

- Clipboard Management

Now that we use copyq we can do stuff. For example display a confirmation window before each paste. But that still seems a bit harsh to me! We can also recommend activating a password (https://copyq.readthedocs.io/en/latest/password-protection.html). What do you have in mind?

@adamkrellenstein also what do you mean by Information Flow Control and Shell Prompt

**Comment by adamkrellenstein** [comment]
> * Window Borders

I was thinking we'd do this at the WM level. Qubes also does this, fwiw.


> * Clipboard Management
> 
> Now that we use copyq we can do stuff. For example display a confirmation window before each paste. But that still seems a bit harsh to me! We can also recommend activating a password (https://copyq.readthedocs.io/en/latest/password-protection.html). What do you have in mind?

I think we should have a confirmation prompt, with the name of the source and target hosts in it, but there's no need for a password.


> @adamkrellenstein also what do you mean by Information Flow Control and Shell Prompt

I think we can skip Information Flow Control. It's too advanced.

By "shell prompt", I just mean we should have a differently colored shell prompt for each host (when `ssh`ing into them).

**Comment by ouziel-slama** [comment]
@adamkrellenstein see
shell prompt: https://github.com/towercomputers/toweros/issues/160
windows border: https://github.com/towercomputers/toweros/issues/161
paste confirmation: https://github.com/towercomputers/toweros/issues/162

shell prompt is done.
For window border I find it annoying that we are dependent on a WM... and also which one? xfce4 until there is an apk for xfce wayland? we could also use wayland + labwc (https://github.com/labwc/labwc) which also works well with NX.
Same for confirming the paste, before implementing something you have to know which WM you want to use.

**Comment by adamkrellenstein** [comment]
Yeah, I think it makes sense to just jump straight to wayland and labwc for v0.1.8

**Comment by ouziel-slama** [comment]
great I moved https://github.com/towercomputers/toweros/issues/60 into v0.1.8

**Comment by ouziel-slama** [comment]
@adamkrellenstein of for you to close this one ? we have https://github.com/towercomputers/toweros/issues/161 and https://github.com/towercomputers/toweros/issues/162.

**Comment by adamkrellenstein** [comment]
yep!
